### ISSUE TITLE
Publish 1.0.0-beta to npm

### ISSUE THREAD

**Issue by novacrazy** [gustavohenke/toposort#13]
When you get a chance I think we can publish version 1.0.0-beta to npm and maybe to bower as well.

It turns out I was correct to doubt that offset thing, even though it did increase performance. Most of the time when adding new edges to the dependency graph, they would already be partially sorted just inherently, so in all the tests it never had to do a splice call on anything but the first element.

However, on more complex and random dependency graphs is does make splice calls to other locations. To solve this I combined both methods and now it will splice if it has to, but otherwise it'll just use the offset.

I re-ran the benchmarks and they are still quite a bit better, so I can't complain. 

I also added a minified version to the build that you might prefer go into the bower package instead of the normal one.

**Comment by gustavohenke** [comment]
Done.

```
npm install toposort-class@beta
```

[Can you write the release?](https://github.com/gustavohenke/toposort/releases/tag/1.0.0-beta)
I think you're more aware than I regarding all changes made :)

**Comment by novacrazy** [comment]
And done: [Version 1.0.0-beta](https://github.com/gustavohenke/toposort/releases/tag/1.0.0-beta).

If that looks good to you then go ahead and close this issue.

**Comment by gustavohenke** [comment]
Alright, the next step is to ping Sequelize and see if they want to make some tests!
