### ISSUE TITLE
Provide default instance

### ISSUE THREAD

**Issue by gustavohenke** [gustavohenke/toposort#9]
When `require('toposort-class')`, a default instance could be returned, so the user doesn't have to do `new`.

**Comment by novacrazy** [comment]
Would you mind if I closed this one, too? I don't think having a global instance of it would be a good idea, even with `.clear` added. It would be too easy to have a memory leak since there is always a reference to it.

**Comment by gustavohenke** [comment]
Your pick!

**Comment by novacrazy** [comment]
Alright, closed. Using `new` on a class is expected, I think.
